CREATE TABLE interview_session (
    id    UUID        PRIMARY KEY,
    state VARCHAR(32) NOT NULL
);

CREATE TABLE session_message (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id       UUID         NOT NULL REFERENCES interview_session (id),
    message_position INTEGER      NOT NULL,
    role             VARCHAR(16)  NOT NULL,
    content          TEXT         NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_session_message_order UNIQUE (session_id, message_position)
);

CREATE INDEX idx_session_message_session_id ON session_message (session_id);
